_wandb:
    value:
        cli_version: 0.18.3
        m:
            - "1": batch/batch_step
              "6":
                - 3
              "7": []
            - "1": batch/accuracy
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": batch/loss
              "5": 1
              "6":
                - 1
                - 3
              "7": []
            - "1": batch/learning_rate
              "5": 1
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 95
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
                - 95
            "3":
                - 7
                - 13
                - 16
                - 23
                - 38
                - 55
            "4": 3.11.10
            "5": 0.18.3
            "6": 4.44.2
            "8":
                - 5
            "12": 0.18.3
            "13": darwin-arm64
        visualize:
            Training Accuracy per epoch:
                panel_config:
                    fieldSettings:
                        stroke: null
                        x: epoch
                        "y": acc
                    panelDefId: wandb/line/v0
                    stringSettings:
                        title: Training Accuracy per epoch
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Training Accuracy per epoch_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            Training Loss epoch:
                panel_config:
                    fieldSettings:
                        stroke: null
                        x: epoch
                        "y": loss
                    panelDefId: wandb/line/v0
                    stringSettings:
                        title: Training Loss epoch
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Training Loss epoch_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            Validation Accuracy per epoch:
                panel_config:
                    fieldSettings:
                        stroke: null
                        x: epoch
                        "y": val_acc
                    panelDefId: wandb/line/v0
                    stringSettings:
                        title: Validation Accuracy per epoch
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Validation Accuracy per epoch_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
            Validation Loss per epoch:
                panel_config:
                    fieldSettings:
                        stroke: null
                        x: epoch
                        "y": val_loss
                    panelDefId: wandb/line/v0
                    stringSettings:
                        title: Validation Loss per epoch
                    transform:
                        name: tableWithLeafColNames
                    userQuery:
                        queryFields:
                            - args:
                                - name: runSets
                                  value: ${runSets}
                              fields:
                                - fields: []
                                  name: id
                                - fields: []
                                  name: name
                                - fields: []
                                  name: _defaultColorIndex
                                - args:
                                    - name: tableKey
                                      value: Validation Loss per epoch_table
                                  fields: []
                                  name: summaryTable
                              name: runSets
                panel_type: Vega2
batch_size:
    value: 1
class_imbalance:
    value: true
dataset:
    value: openai/gsm8k
device_map:
    value: auto
epochs:
    value: 25
filename:
    value: runs/openai-gsm8k/processed_ds/llama3_gsm8k_train_test_balanced.xlsx
fix_class_imbalance:
    value: true
hidden_layer:
    value: -1
load_in_4bit:
    value: true
load_in_8bit:
    value: false
max_new_tokens:
    value: 256
model_hf_key:
    value: meta-llama/Meta-Llama-3.1-8B-Instruct
read_from_file:
    value: false
regression_features_path:
    value: runs/openai-gsm8k/2024-10-22_08-16-15/regression_features.txt
regression_features_saved:
    value: false
regression_labels_path:
    value: runs/openai-gsm8k/2024-10-22_08-16-15/regression_labels.txt
regression_model:
    value: feed forward
samples:
    value: 10
togetherai:
    value: true
verbose:
    value: false
